version: "3.8"

services:
  app:
    restart: unless-stopped
    container_name: domyno
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
#    volumes:
#      - .:/app
#      - '/app/node_modules'
    depends_on:
      - mysql
    stdin_open: true
    tty: true

  mysql:
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - '/var/lib/mysql'


  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin:latest
    ports:
      - $PHPMYADMIN_LOCAL_PORT:$PHPMYADMIN_DOCKER_PORT
    environment:
      - PMA_HOST=$MYSQLDB
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - PMA_USER=$MYSQLDB_USER
      - PMA_PASSWORD=$MYSQLDB_ROOT_PASSWORD
